### ISSUE TITLE
Load all other rules if validation (of one rule) fails

### ISSUE THREAD

**Issue by phoenix1589** [capnspacehook/whalewall#71] opened 2023-03-21 10:08 UTC
If a rule is specified for a container that allows outbound traffic to another container, but that other container isn't currently running, whalewall currently produces an error:
``` 
whalewall.rules: |
        mapped_ports:
          external:
            allow: true
            ip: "172.16.0.0/24"
        output:
          - network: network_name
            container: destination_container
            proto: tcp
            port: 80 
``` 
`{"level":"error","time":"2023-03-21T09:17:58.059162191Z","msg":"error creating rules","container.id":"6f605f87008c","container.name":"<container_with_ruleset>","error":"error validating rules: output rule #3: container \"<destination_container>\" not found">`

If this happens, no other rules are applied - meaning the mapped_ports are allowed from anywhere, rather than just the IP specified in the rule.

Would it be possible to ignore the rule relating to the not found container, but still apply all other rules listed?

**Comment by capnspacehook** [comment] 2023-04-07 15:29
I pushed a fix a few days ago that should resolve your specific error, as now Whalewall will wait to create container -> container rules until the destination container is created. You bring up a good point though, that rules should probably be created on a best effort basis, instead of all or nothing as it is now. The problem is that would be difficult to implement accounting for all edge cases... 

Can you pull the latest Docker image or build from master and see if your problem is solved?

**Comment by capnspacehook** [comment] 2023-06-13 12:09
Rules are now applied in small independent batches on a best effort basis, so if some rules fail to be creation of other rules will still be attempted.

**Closed by capnspacehook** 2023-06-13 12:09 UTC
Labels: enhancement, question
